CREATE TABLE [dbo].[TodoItem] (
	[TodoItemId] INT NOT NULL IDENTITY PRIMARY KEY
	, [DueDate] DATETIME NOT NULL
	, [Title] NVARCHAR(50) NOT NULL
	, [Status] NVARCHAR(50) NOT NULL
	, [UserId] INT
	, CONSTRAINT [FK_User_TodoItem] FOREIGN KEY ([UserId]) REFERENCES [User]([UserId])
	)