CREATE TABLE [dbo].[User] (
	[UserId] INT NOT NULL IDENTITY PRIMARY KEY
	, [Email] NVARCHAR(255) NOT NULL
	, [FirstName] NVARCHAR(50)
	, [LastName] NVARCHAR(50)
	, [Password] NVARCHAR(MAX) NOT NULL
	)